package com.ds.linear;

import com.ds.base.Node;

import junit.framework.TestCase;

public class StackTest extends TestCase {

    public void test_type() throws Exception {
        // TODO auto-generated by JUnit Helper.
        assertNotNull(Stack.class);
    }

    public void test_instantiation() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack<String> target = new Stack<String>();
        assertEquals(-1, target.getTop());
        assertNotNull(target.getStart());
        assertNull(target.getStart().getNext());
        assertNull(target.getStart().getData());
    }

    public void test_print_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack target = new Stack();
        target.print();
    }

    public void test_pop_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack target = new Stack();
        Boolean flag = false;
        try {
            Object actual = target.pop();
        } catch (Exception actual) {
            flag = true;
        }
        assertEquals(-1, target.getTop());

    }

    public void test_pop_A$_T$Exception() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack<String> target = new Stack<String>();
        try {
            target.push("Adam");
            target.pop();
        } catch (Exception e) {
        }

        assertEquals(-1, target.getTop());

    }

    public void test_push_A$Object() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack<String> target = new Stack<String>();

        target.push("Adam");
        target.push("Sandra");
        target.push("Peter");
        target.push("Mike");
        target.push("Falco");
        assertEquals(4, target.getTop());

    }

    public void test_getStart_A$() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack<Object> target = new Stack<Object>();
        Node<Object> actual = target.getStart();
        assertNotNull(actual);
    }

    public void test_setStart_A$Node() throws Exception {
        // TODO auto-generated by JUnit Helper.
        Stack<Object> target = new Stack<Object>();
        Node<Object> start = null;
        target.setStart(start);
    }

    public void test_main_A$StringArray() throws Exception {
        // TODO auto-generated by JUnit Helper.
        String[] args = new String[] {};
        Stack.main(args);
    }

    public void test_main_A$StringArray_T$Exception() throws Exception {
        // TODO auto-generated by JUnit Helper.
        String[] args = new String[] {};
        try {
            Stack.main(args);
        } catch (Exception e) {
        }
    }

    public void testContains() throws Exception {
        Stack<String> target = new Stack<String>();

        target.push("Adam");
        target.push("Sandra");
        target.push("Peter");
        assertEquals(target.contains("Adam"), new Boolean(true));
        assertEquals(target.contains("Ram Ram g"), new Boolean(false));

    }

}
